version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      go-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      npm-deps:
        patterns:
          - "*"
