version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      go-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - "*"