runtime: go114
service: penelope
handlers:
  -   url: /
      static_files: static/ui/index.html
      upload: static/ui/index.html

  -   url: /static/ui/(images|js|css)/(.*)
      static_files: static/ui/\1/\2
      upload: static/ui/(images|js|css)/(.*)

  -   url: /.*
      script: auto
      secure: always

env_variables:
  GCP_PROJECT_ID: <GCP_PROJECT_ID>
  PENELOPE_PORT: <PENELOPE_PORT>
  POSTGRES_SOCKET: /cloudsql/<GCP_PROJECT>:<REGION>:<DB_INSTANCE>/.s.PGSQL.5432
  POSTGRES_USER: <POSTGRES_USER>
  POSTGRES_DB: <POSTGRES_DB>
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  DEFAULT_PROVIDER_BUCKET: <DEFAULT_PROVIDER_BUCKET>
  DEFAULT_BACKUP_SINK_PROVIDER_FOR_PROJECT_FILE_PATH: <DEFAULT_BACKUP_SINK_PROVIDER_FOR_PROJECT_FILE_PATH>
  DEFAULT_USER_PRINCIPAL_PROVIDER_FILE_PATH: <DEFAULT_USER_PRINCIPAL_PROVIDER_FILE_PATH>
  DEFAULT_PROVIDER_IMPERSONATE_GOOGLE_SERVICE_ACCOUNT: <DEFAULT_PROVIDER_IMPERSONATE_GOOGLE_SERVICE_ACCOUNT>
  DEFAULT_BUCKET_STORAGE_CLASS: REGIONAL
  APP_JWT_AUDIENCE: <APP_JWT_AUDIENCE>
  PENELOPE_TRACING: <true/false>
  PENELOPE_TRACING_METRICS_PREFIX: <PENELOPE_TRACING_METRICS_PREFIX>
  TOKEN_HEADER_KEY: <TOKEN_HEADER_KEY>
  COMPANY_DOMAINS: <COMPANY_DOMAINS>
  CORS_ALLOWED_METHODS: 'POST, PATCH, GET'
  CORS_ALLOWED_ORIGIN: '*'
  CORS_ALLOWED_HEADERS: 'Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization'
  TASKS_VALIDATION_HTTP_HEADER_NAME: 'X-Appengine-Cron'
  TASKS_VALIDATION_HTTP_HEADER_VALUE: 'true'
  TASKS_VALIDATION_ALLOWED_IP_ADDRESSES: '10.0.0.1;0.1.0.1'