name: Go

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: backupdatabase
      POSTGRES_USER: backupuser
      POSTGRES_PASSWORD: backupuserpassword
      POSTGRES_PORT: 5432
    services:
      postgres:  
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_DB: backupdatabase
          POSTGRES_USER: backupuser
          POSTGRES_PASSWORD: backupuserpassword
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Install Flyway
        run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.9.0/flyway-commandline-9.9.0-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-9.9.0/flyway /usr/local/bin
      
      - name: DB Migration
        run: flyway migrate -url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -locations=filesystem:./resources/migrations

      - name: Set up Go ^1.20
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: |
          set -o pipefail
          GOOGLE_APPLICATION_CREDENTIALS="$(PWD)/resources/credentials/fake-service-account.json"
          mkdir output
          go test -v -p 1 ./... | tee output/tmp-test-output.txt

      - name: Testing Report
        if: always()
        run: ./.github/scripts/report.sh output/tmp-test-output.txt

      - name: Build
        run: go build -v ./...

      - name: Static Folder Artifact
        uses: actions/upload-artifact@v2
        with:
          name: static-folder
          path: static
