name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:  
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_DB: backupdatabase
          POSTGRES_USER: backupuser
          POSTGRES_PASSWORD: backupuserpassword
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Install Flyway
        run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.3.1/flyway-commandline-7.3.1-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-7.3.1/flyway /usr/local/bin
      
      - name: DB Migration
        run: flyway migrate -url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -locations=filesystem:./resources/migrations
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: backupdatabase
          POSTGRES_USER: backupuser
          POSTGRES_PASSWORD: backupuserpassword

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -p 1 -v 
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: backupdatabase
          POSTGRES_USER: backupuser
          POSTGRES_PASSWORD: backupuserpassword
